services:
    portal:
        command: npm run dev:next
        image: ux/portal:latest
        environment:
            NODE_ENV: development
        volumes:
            - ../:/app
        ports:
            - '3000:3000'
